export const DEFAULT_PRIMARY_CURRENCIES = ["USD", "PLN", "CZK", "AUD"];
export const DEFAULT_SECONDARY_CURRENCIES = ["PLN", "BRL", "CAD", "DKK"];
export const DEFAULT_PRIMARY_CURRENCY = "USD";
export const DEFAULT_SECONDARY_CURRENCY = "PLN";

export const DEFAULT_PRIMARY_CRYPTO_CURRENCIES = ["BTC", "SOL", "ETH", "DOGE"];
export const DEFAULT_SECONDARY_CRYPTO_CURRENCIES = ["USDT", "ETH", "BNB", "ADA"];
export const DEFAULT_PRIMARY_CRYPTO_CURRENCY = "BTC";
export const DEFAULT_SECONDARY_CRYPTO_CURRENCY = "USDT";
